name: Publish the released PHAR

on:
    push:
        tags:
            - "v*"

jobs:
    publish:
        runs-on: ubuntu-22.04

        name: Release PHAR

        steps:
            - name: Extract the tag version
              id: tag
              run: echo "tag=${GITHUB_REF##*v}" >> "$GITHUB_OUTPUT"

            - name: Checkout the code
              uses: actions/checkout@v4
              with:
                  ref: v${{ steps.tag.outputs.tag }}

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.2
                  ini-values: error_reporting=E_ALL
                  tools: composer:v2, box
                  coverage: none

            - name: Install the dependencies
              run: composer install --prefer-dist --no-progress

            - name: Create the PHAR file.
              run: box compile --quiet

            - name: List files after build
              run: |
                  echo "Current directory:"
                  pwd
                  echo "Contents:"
                  ls -R

            - name: Commit PHAR
              run: |
                  git config user.name "GitHub Actions"
                  git config user.email "actions@github.com"
                  git add bin/zed-pint
                  git commit -m "Build PHAR for $GITHUB_REF_NAME [skip ci]" || echo "No changes to commit"
                  git push origin HEAD:refs/heads/${GITHUB_REF##*/}
